name: Test Build

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
        id: go
      - name: Get dependencies
        run: |
          go mod download
      - name: Build
        run: |
          GOOS=linux GOARCH=arm64 go build -v -o ${GITHUB_REPOSITORY##*/}-linux-arm64 ./cmd/...
